### PR TITLE
Reach out to ubuntu keyserver on port 80

### PR DESCRIPTION
**Pull request by yuvipanda**
mybinder.org blocks outgoing port 400 (the default gpg
keyserver port), so this image never builds there.
ubuntu keyserver supports port 80 too, and we can explicitly
mention it here so our builds work on mybinder.org

### CODE REVIEW

**Review by damianavila — APPROVED** [review]
51 min to build the image... wondering if we can reduce that somehow 🤔  
In any case, not a blocker to merge this one!

**Comment by yuvipanda** [comment]
Ya I agree we should do something about it - plenty of options to make things better here...

**Comment by damianavila** [comment]
Should we capture that discussion in some issue, maybe?

**Comment by yuvipanda** [comment]
@damianavila opened https://github.com/2i2c-org/utoronto-image/issues/4

**Pull request merged**
