### PR TITLE
Simplify image vastly, get rid of R

### PR DESCRIPTION
**Pull request by yuvipanda**
- Inherit from jupyter/scipy-notebook, so we can reuse all the
   work in terms of setting up jupyterhub, conda, base scientific
   packages, etc. In particular, this should also load the env
   variables set by conda packages (like pyproject), solving
   https://github.com/2i2c-org/infrastructure/issues/2479
 - Install only extra packages we want on top, prefering conda wherever
    possible. Bump up versions to latest.
 - Get rid of everything R related, as those must move to the R hub.
    
 Fixes https://github.com/2i2c-org/infrastructure/issues/2479
 Ref https://github.com/2i2c-org/infrastructure/issues/2583 to
 reduce complexity of our images.

### CODE REVIEW

**Comment by damianavila** [comment]
There is a build failure:

```

 ---> Running in 55e452c14302
  
  
  Looking for: ['websockify', 'python=3.10', 'networkx=3.1', 'nltk=3.8', 'spacy=3.5', 'geopandas=0.13', 'geopy=2.3', 'astroquery=0.4', 'astropy==5.3', 'galpy=1.8', 'libgfortran==3.0.0', 'tensorflow=2.12', 'nbgitpuller=1.1', 'jupyter-resource-usage=0.7', 'jupytext=1.14', 'rise==5.7.1', 'jupyter_contrib_nbextensions==0.7.0', 'jupyter-server-proxy=4', 'contextily=1.3', 'libpysal=4.7', 'esda=2.4', 'splot=1.1', 'xlrd=2.0', 'numba=0.57', 'python-graphviz=0.20', 'pip']
  
  
  
    Pinned packages:
  
    - python 3.11.4
  
  
  Could not solve for environment specs
  The following packages are incompatible
  ├─ python 3.10**  is requested and can be installed;
  └─ tensorflow 2.12**  does not exist (perhaps a typo or a missing channel).
  Removing intermediate container 55e452c14302
  The command '/bin/bash -o pipefail -c mamba env update -p ${CONDA_DIR} -f /tmp/environment.yml && mamba clean -afy' returned a non-zero code: 1
```

**Comment by yuvipanda** [comment]
Current problem:

```
 Could not solve for environment specs
  The following packages are incompatible
  ├─ libre2-11 is installable and it requires
  │  └─ libabseil >=20230802.1,<20230803.0a0 , which can be installed;
  └─ tensorflow 2.13**  is installable with the potential options
     ├─ tensorflow 2.13.1 would require
     │  └─ tensorflow-base 2.13.1 cpu_py311ha0be21f_1, which requires
     │     └─ libabseil >=20230125.3,<20230126.0a0 , which conflicts with any installable versions previously reported;
     ├─ tensorflow 2.13.1 would require
     │  └─ python >=3.10,<3.11.0a0 , which can be installed;
     ├─ tensorflow 2.13.1 would require
     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
     ├─ tensorflow 2.13.1 would require
     │  └─ python >=3.9,<3.10.0a0 , which can be installed;
     └─ tensorflow 2.13.1 would require
        └─ __cuda, which is missing on the system.
```

But idk what package actually requires  ` libre2-11`

**Comment by yuvipanda** [comment]
This builds if I get rid of `tensorflow`, and I suspect https://github.com/conda-forge/tensorflow-feedstock/pull/353 may fix that. In the meantime, I am just getting tensorflow from PyPI.

https://github.com/conda-forge/rise-feedstock/issues/43 is causing RISE to fail to install from conda-forge as well.

**Comment by yuvipanda** [comment]
Merging so we can deploy to staging and test.

**Pull request merged**
