### PR TITLE
Add graphviz as an apt package

### PR DESCRIPTION
**Pull request by consideRatio**
I'm not sure on the procedure for handling these images overall, but I went for this PR as a start to meet the request in https://2i2c.freshdesk.com/a/tickets/697.

@yuvipanda what are the next steps in this situation?

Things like ask for review, merge on successful build, do something in the 2i2c-org/infrastructure's utoronto chart config are possible actions that popped into my mind.

### CODE REVIEW

**Comment by jmunroe** [comment]
This PR only captures the operating system's `graphviz` package. Won't Python bindings be needed as well? (Something like `python-graphviz` from conda forge?)

I recall some issues with graphviz / python-graphviz and personally have usually installed both from conda-forge. Those issues may only be historical though so perhaps the `apt` install is fine.

**Comment by yuvipanda** [comment]
I agree with @jmunroe that adding `python-graphviz` from conda-forge (which also brings in graphviz from conda-forge) is the way to go. It would also give us a newer version of graphviz than from apt.

**Comment by pnasrat** [comment]
@consideRatio just pinging this as this is for a support issue can you make the suggested changes to use conda-forge python-graphviz and I can review.

**Comment by consideRatio** [comment]
Thanks for the ping @pnasrat and directions on how to install this @jmunroe and @yuvipanda!

>@yuvipanda what are the next steps in this situation?
>
>Things like ask for review, merge on successful build, do something in the 2i2c-org/infrastructure's utoronto chart config are possible actions that popped into my mind.

@yuvipanda @pnasrat @jmunroe this is an open question still for me, what are the practical next steps to meet the expectations set by past interactions to help utoronto with their images?

- Next step we merge this?
- Then an automated PR is opened to bump this in 2i2c-org/infrastructure perhaps? Maybe not, its not [listed in here](https://github.com/2i2c-org/infrastructure/blob/master/.github/workflows/bump-image-tags.yaml#L27-L39), should it be?
- Then I test the image on staging.utoronto.2i2c.cloud using the configurator? Maybe not, I saw that I'm not an admin there, so I can't use it, so this is perhaps what we ask Scott who requested graphviz to do?
- Then we merge the PR to bump the image after Scott has said its all ok?

**Comment by consideRatio** [comment]
@pnasrat looking at https://github.com/2i2c-org/utoronto-r-image/pull/3#issuecomment-1559748596 it seems you merged and tested on staging - I presume using the configurator. Could you add me as an admin on staging via `/hub/admin`?

I'm the user `2a2d9b48-e6eb-46e1-8434-8aaeb7a98dd8`

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/utoronto-image/pull/51#issuecomment-1560143055 sounds right to me

**Comment by pnasrat** [comment]
@consideRatio we don't use configurator/have admin on the utoronto hubs so for testing I created an override in the staging values.yaml and deployed manually to test - see below. 

https://github.com/2i2c-org/infrastructure/pull/2573/files

**Comment by pnasrat** [comment]
To test graphviz I'd probably create a simple dot file (probably a digraph) and run from the terminal, and check the outputthen also check that a simple graph renders in Jupyter

https://graphviz.readthedocs.io/en/stable/manual.html#jupyter-notebooks

**Comment by consideRatio** [comment]
Thank you @pnasrat and @yuvipanda !

**Pull request merged**
